# -*- coding: utf-8 -*-
"""fastApi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193eVZ2KgPZb_8ZQ8Jt8G_hJs10-v4Rs2
"""

!pip install fastapi uvicorn nest_asyncio

!pip install pyngrok

!ngrok config add-authtoken 2oai5oSu9VZwg9skxUGEOWddpg8_2XqVtVH6kBVPyy1sVfMU7

import threading
import nest_asyncio
import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel
import numpy as np
from typing import List
from pyngrok import ngrok
import xgboost as xgb

# Inicializar la aplicación FastAPI
app = FastAPI()

#*************api modelo*********************
# Cargar el modelo con manejo de excepciones

try:
    model = xgb.Booster()
    model.load_model('/content/xgboost-model')
    print("Modelo cargado correctamente.")
except Exception as e:
    print(f"Error al cargar el modelo: {e}")


# Definir un modelo de datos para recibir las entradas
#class DataPayload(BaseModel):
class InputData(BaseModel):
    data: List[float]

# Endpoint para hacer predicciones
@app.post("/predict/")
async def predict(payload: InputData):
    try:
        # Extraer los datos del payload
        data = np.array(payload.data).reshape(1, -1)

        # Convertir el numpy.ndarray a DMatrix
        dmatrix_data = xgb.DMatrix(data)

        # Realizar la predicción
        prediction = model.predict(dmatrix_data)

        # Mapear el valor de la predicción a una etiqueta
        label_map = {0: "low_value", 1: "medium_value", 2: "high_value"}
        predicted_label = label_map.get(prediction[0], "unknown")

        return {"predicted_label": predicted_label}

    except Exception as e:
        print(f"Error en la predicción: {e}")
        return {"error": str(e)}


#****************************************************

# Permite que FastAPI ejecute dentro de Colab
nest_asyncio.apply()

# Función para ejecutar el servidor en un hilo
def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8000)

# Ejecutar el servidor en un hilo separado
thread = threading.Thread(target=run_server)
thread.start()

# Crear un túnel a través de ngrok
public_url = ngrok.connect(8000)
print(f"FastAPI is accessible at: {public_url}")

!curl -X POST https://0cdd-34-106-7-115.ngrok-free.app/predict/ -H "Content-Type: application/json" -d '{"data": [0.812959, 0, -0.560700, 1.701895, -1.478080, -0.121517, 0.125643, 0, 0.489832, 0.340994]}'